### ISSUE TITLE
🚀 feat: FacilityFragment UI 구현

### ISSUE THREAD

**Issue by Seon-Ju** [HeyHong/heyhong-android#3]
## 🏠 Feature Issue
FacilityFragment UI 구현

## 📝 To-do
- [ ]  전체적인 UI 구현
- [ ]   spinner 구현
- [ ]  강의실 설명(classdesc) null값일 시 setVisibility 설정
- [ ]   댓글 버튼 누르면 펼쳐지게
